version: '3.8'

services:
  backend:
    build: ./backend
    container_name: atnaltik_backend
    restart: always
    env_file: ./backend/.env
    volumes:
      - ./backend/atnaltik_v2_session.session:/app/atnaltik_v2_session.session
      - ./backend/atnaltik.db:/app/atnaltik.db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: atnaltik_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
